version: 2.1

defaultImage: &defaultImage
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaultImage
    steps:
      - checkout
      - run: npm i
      - save_cache:
          - key: npm-packeges
          - paths: ~/node_modules
      - run: npm run lint
  test:
    <<: *defaultImage
    steps:
      - checkout
      - restore_cache:
          - key: npm-packeges
      - run: npm i
      - run: npm run test
  analyze:
    <<: *defaultImage
    steps:
      - checkout
      - run: npm audit

workflows:
  first_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
